spring:
 profiles:
  active:
   - dev
    
---
spring:
 profiles: dev 
  application:
   name: microservicecloud-config-ethan-dev
---
spring:
 profiles: test 
  application:
   name: microservicecloud-config-ethan-test